def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]

pipeline {
    
	agent any
/*	
	tools {
        maven "maven3"
    }
*/	
    environment {
        cluster = "vproappprod"
        service = "vproappprodsvc"
    }
	
    stages{
        stage('Deploy to ECS Staging') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }


    }
        post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#vprofile-cicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}" 
        }
    }
}



